version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=test_task2.settings
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
    depends_on:
      - web
    restart: unless-stopped
  
  postgres:
    container_name: test_task2-postgres
    image: postgres:14.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_task2
      - POSTGRES_USER=test_task2
      - POSTGRES_PASSWORD=test_task2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped